README.md, test/index.spec.js
addresses https://github.com/ipfs/js-ipfs/issues/117
=> 100% coverage

.npmignore, package.json
```
12 04 2016 21:06:03.040:INFO [launcher]: Starting browser PhantomJS
12 04 2016 21:07:03.039:WARN [launcher]: PhantomJS have not captured in 60000 ms, killing.
12 04 2016 21:07:05.040:WARN [launcher]: PhantomJS was not killed in 2000 ms, sending SIGKILL.
12 04 2016 21:07:07.045:WARN [launcher]: PhantomJS was not killed by SIGKILL in 2000 ms, continuing.
```
=> jsnext add

src/index.js, test/index.spec.js
While investigating slow performance in js-ipfs I discovered that there are too many calls to `mh.toB58String`. This is the start of reducing the number of those calls.
=> feat: cache b58 id

src/index.js, test/peer-id.spec.js
hey @diasdavid , I noticed that whenever ipfs creates an Id , it usually uses `peerId.createFromPrivKey` , and this means you can add pubkey to the `PeerId` constructor call.
This is useful because it means the pubKey is available without ever triggering `get pubKey()`. so when this peer connects to another, the `peer-id` object would have the pubKey included. and won't equal `undefined` like the current situation.
I Also added a line to the tests to check if the pub key is valid.
=> Always add public key to constructor if possible, Fix for undefined pubKey in remote peers

.gitignore, package.json, src/index.js, test/peer-id.spec.js
=> Catch error when unmarshaling instead of crashing

README.md, package.json, src/bin.js, src/index.js, test/peer-id.spec.js
More background about this effort: https://github.com/ipfs/js-ipfs/issues/1670.
~Despite some `createX` function not needing `async`, I added it to all of them to make them consistent. Otherwise we would have half returning a Promise and another half returning a PeerId~
=> feat: async await

README.md, package.json, src/index.js, test/peer-id.spec.js
Support creating peer IDs from Secp256k1 type keys and harmonize ID algorithm with Go so that for public keys of <= 42 bytes length, we inline the public key.
Required by https://github.com/libp2p/interop/pull/21
=> Support creating from Secp256k1 / harmonize algorithm with Go

package.json, src/bin.js
This reverts async to the 2.6 line as 3.0 has issues https://github.com/libp2p/js-peer-id/issues/96#issuecomment-513873738.
**Note** this merge is into a 0.12.x branch. Since 0.13 is already out and is leveraging the async/await codebase, we need to release from the latest 0.12 tag. 0.12.x is based off of that latest release. Once released, I will delete that branch as well.
=> chore: revert async dep change

src/index.js, test/peer-id.spec.js
We are having trouble because we are using Secp256k1 from Go in our pubsub messages. Go does not set the "key" field of a message when publishing with an inline key. So javascript rejects any signed Go message (using Secp256k1).
There is a TODO here: https://github.com/libp2p/js-libp2p-pubsub/blob/master/src/message/sign.js#L76-L77
Well, hopefully this PR allows for that TODO to happen. 
All this does is check if the peerID has identity encoding and if it does, attempt to recover the public key from the encoding.
=> support inline public keys

README.md
I spent so long trying to get `PeerId` working with `libp2p-crypto` and eventually had to use
```js
Reflect.ownKeys(Reflect.getPrototypeOf(Reflect.getPrototypeOf(pid)))
```
to find this function.
Why was it not included already? It seems pretty useful.
=> include `marshalPubKey` and example

README.md, package.json, src/index.js, test/peer-id.spec.js
This PR implements `Stage 1: Parse CIDs as peer ID` from https://github.com/libp2p/specs/issues/216. 
**TL;DR** This PR does not change the default text representation of Peer IDs, all we do in `Stage 1` is adding support for creating PeerId objects from CIDs.  
For a wider context see [libp2p/specs/RFC/0001-text-peerid-cid.md](https://github.com/libp2p/specs/blob/master/RFC/0001-text-peerid-cid.md), short story is that CID support will enable IPFS project to support `/ipns/{cid}` in Base32 (https://github.com/ipfs/ipfs/issues/337), enabling things like `http://{libp2p-key-as-cidv1b32}.ipns.dweb.link`
This PR adds two functions:
- `createFromCID` accepts CID as String|CID|Buffer and creates PeerId from the multihash value inside of it
- `toCIDString` serializes PeerId multihash into a …
=> feat: support Peer ID represented as CID

README.md, src/index.js, test/peer-id.spec.js
Resolves https://github.com/libp2p/js-peer-id/issues/94.
This deprecates isEqual in favor of `equals`. I added a deprecation notice to the readme about removing support for this whenever we release 0.14. If this looks good I will create an issue to track its removal.
=> feat: deprecate isEqual in favor of equals

src/index.js
`multihash.decode` throws an error, and we are not catching that, this fixes that. We shouldn't need to throw this error. This will occur if no public key exists, and the Id doesn't contain a valid multihash code. The decode was added to unmarshal inline public keys.
=> fix: catch errors thrown by multihash decode

package.json, src/index.d.ts, test/peer-id.spec.js, tsconfig.json
Depends on https://github.com/multiformats/js-cid/pull/102 for tests to run/work nicely, but this PR is already useful on its own if you don't want to use the tests in CI etc.
=> feat: adds typescript types + type tests

src/index.d.ts
This tells Typescript that `id` is immutable.
=> Improve typings

src/index.d.ts
Tell Typescript that `isPeerId(id)` returns true if, and only if, `id` is of type `PeerId`.
See https://www.typescriptlang.org/docs/handbook/advanced-types.html#using-type-predicates
=> Add type predicate

README.md, package.json, src/bin.js, test/peer-id.spec.js
This adds the ability to specify the key type and size when using the cli.
```console
$ peer-id --type ed25519
{
"id": "12D3Koo...",
"privKey": "CAES...",
"pubKey": "CAE..."
}
```
```console
$ peer-id --type rsa --bits 4096
{
"id": "Qm...",
"privKey": "CAA...",
"pubKey": "CAA..."
}
=> feat(cli): add support for specifying type and size

.aegir.js, package.json, src/index.d.ts, src/index.js, test/peer-id.spec.js
Replaces all uses of node Buffers with Uint8Arrays
Depends on:
BREAKING CHANGES:
- Where node Buffers were returned, now Uint8Arrays are
=> fix: replace node buffers with uint8arrays

src/index.d.ts
If `pubKey` can be undefined then the `privKey` should be possible to have undefined as well.
=> fix: privKey possible undefined

src/index.d.ts, src/index.js, test/peer-id.spec.js
There are several use cases where it is important to know if the peerId has inline public key
Closes #131
=> feat: has inline public key method

README.md
Typescript complains if you use `rsa` instead of `RSA` for the keyType so this will correct the examples in the documentation to match the [keyType exported from libp2p-crypto](https://github.com/libp2p/js-libp2p-crypto/blob/b28c232e227055beed990945c795a27bacff56e5/src/index.d.ts#L4).
=> docs: correct case for RSA keyType

src/index.js, test/peer-id.spec.js
Makes the cached string cid property non-enumerable so deep equals
still works even after a peer id has been stringifed.
Fixes #141
=> fix: remove toString side effect that breaks deep equals

.aegir.js, package.json, src/index.d.ts, src/index.js, test/peer-id.spec.js, tsconfig.json
PeerIds used by ipns pubsub are base36 encoded so support parsing
peer IDs out of base36 encoded strings.  In fact, just support
every default encoding supported by multiformats.
Also removes multihashes dep as we don't need it any more.
=> fix: decode more multibase types

src/index.js
Respect the `PeerId#privKey` typescript type, which is `PrivateKey | undefined`, not `PrivateKey | null`
Found this in the course of manually creating a peer id using typescript.
```ts
import {expect} from "chai";
import PeerId from "peer-id";
import mh from "multihashes";
import { keys } from "libp2p-crypto";
const { supportedKeys } = keys;
async function test () {
const privKey = await supportedKeys.secp256k1.generateKeyPair();
const pubKey = privKey.public;
const id = mh.encode(pubKey.bytes, "identity");
// these two should be identical
const manualPeerId = new PeerId(id, undefined, pubKey); 
const peerId = await PeerId.createFromPubKey(pubKey.bytes);
// but they aren't
expect(manualPeerId).to.deep.equal(peerId);
// replace 'undefined' with 'null as any' to avoid error
}
test();
```
=> Use undefined instead of null privKey

.github/workflows/main.yml
`ursa-optional` has gone from the dep tree so @mapbox/node-pre-gyp shouldn't be required now.
=> chore: remove pre-gyp from ci

README.md
Repo is being deprecated from https://github.com/libp2p/js-libp2p/releases/tag/v0.37.0 in favour of https://github.com/libp2p/js-libp2p-peer-id
Needs:
After merged, the repo must be archived
=> chore: deprecate repo
